package dev.darshan.agentrouter.reliability;

public enum ReasonCode {
    ACCEPTED,
    INVALID_OPERATION_ID,
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    IDEMPOTENT_DUPLICATE,
    IDEMPOTENCY_CONFLICT,
    OPERATION_ID_CONFLICT,
    ADMISSION_SATURATED,
    DEADLINE_EXPIRED,
    BACKEND_UNAVAILABLE,
    BACKEND_AMBIGUOUS,
    CANCEL_REQUESTED,
    CANCEL_CONFIRMED,
    COMPLETION_WINS,
    FAILURE_WINS,
    INVALID_STATE,
    INTEGRITY_FAILURE,
    UNAVAILABLE_PREREQUISITE
}
